---

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - pip install .
script:
  # Workaround for https://github.com/pytest-dev/pytest-cov/issues/98
  - (cd tests && pytest --cov=birdisle --cov-branch) && coverage combine tests/.coverage
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.9 ]]; then flake8; fi
after_success:
  - coveralls
